In [1]:
import numpy as np
import pandas as pd



In [2]:
df = pd.read_csv("Iris-f.csv")
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              NaN           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [6]:
df.fillna(df.mean,inplace=True)

In [4]:
df2= df.copy(deep = True)
df2.dropna(axis=0,inplace = True)
df2.shape

(146, 5)

In [5]:
df1 = df.copy(deep = True)


In [6]:
med = df1['SepalLengthCm'].median()
med

5.8

In [7]:
df1['SepalLengthCm'].fillna(med,inplace=True)
df1.isna().sum()

SepalLengthCm    0
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          1
dtype: int64

In [8]:
df1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.8           3.6            1.4           0.2  Iris-setosa

In [9]:
df1.iloc[[4,7,10,20],:]


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             5.8           3.6            1.4           0.2  Iris-setosa
7             5.0           NaN            NaN           0.2  Iris-setosa
10            5.4           3.7            1.5           0.2          NaN
20            5.8           3.4            1.7           0.2  Iris-setosa

In [10]:
df1.mean()

/tmp/ipykernel_7331/2053335143.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1.mean()


SepalLengthCm    5.851333
SepalWidthCm     3.051678
PetalLengthCm    3.773826
PetalWidthCm     1.198667
dtype: float64

In [11]:

df1.fillna(df.mean(),inplace = True) #or median also cN BE USed
df1.iloc[[4,7,10,20],:]

/tmp/ipykernel_7331/1056798112.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1.fillna(df.mean(),inplace = True) #or median also cN BE USed


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             5.8      3.600000       1.400000           0.2  Iris-setosa
7             5.0      3.051678       3.773826           0.2  Iris-setosa
10            5.4      3.700000       1.500000           0.2          NaN
20            5.8      3.400000       1.700000           0.2  Iris-setosa

In [12]:
df3= df.copy(deep = True)

df3.iloc[[4,7,10,20],:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             NaN           3.6            1.4           0.2  Iris-setosa
7             5.0           NaN            NaN           0.2  Iris-setosa
10            5.4           3.7            1.5           0.2          NaN
20            NaN           3.4            1.7           0.2  Iris-setosa

In [13]:
df3.Species.fillna("Iris-setosa",inplace = True)
df3.iloc[[4,7,10,20],:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             NaN           3.6            1.4           0.2  Iris-setosa
7             5.0           NaN            NaN           0.2  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
20            NaN           3.4            1.7           0.2  Iris-setosa

In [14]:
df4= df.copy(deep = True)
df4.fillna(method="bfill",inplace = True)
df4.head(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.4           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           2.9            1.4           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa

In [15]:
df4.iloc[[4,7,10,20],:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             5.4           3.6            1.4           0.2  Iris-setosa
7             5.0           2.9            1.4           0.2  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
20            5.1           3.4            1.7           0.2  Iris-setosa

In [16]:
df5= df.copy(deep = True)
df5.fillna(method="ffill",inplace = True)
df5.iloc[[4,7,10,20],:]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
4             4.6           3.6            1.4           0.2  Iris-setosa
7             5.0           3.4            1.4           0.2  Iris-setosa
10            5.4           3.7            1.5           0.2  Iris-setosa
20            5.1           3.4            1.7           0.2  Iris-setosa

In [17]:
from sklearn.impute import SimpleImputer
df6= df.copy(deep = True)

In [18]:
si = SimpleImputer(missing_values = np.nan,strategy = "mean")
df6=df.iloc[:,0:4]
si.fit_transform(df6)

array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.1       , 1.5       , 0.2       ],
       [5.85202703, 3.6       , 1.4       , 0.2       ],
       [5.4       , 3.9       , 1.7       , 0.4       ],
       [4.6       , 3.4       , 1.4       , 0.3       ],
       [5.        , 3.05167785, 3.7738255 , 0.2       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       , 1.3       , 0.4       ],
       [5.1       , 3.5       ,

In [19]:
si = SimpleImputer(missing_values = np.nan,strategy = "most_frequent")
# df6=df.iloc[:,0:4]
si.fit_transform(df[['Species']])

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iri

In [20]:
df7= df.copy(deep = True)
df7.dropna(axis=0,inplace=True)
df7.columns
df8=df7[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

In [21]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
scaled=mm.fit_transform(df8)
scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.22222222, 0.70833333,

In [22]:
new_df= pd.DataFrame(scaled,columns=["SL","SW","PL","PW"])
new_df.head()

SL        SW        PL        PW
0  0.222222  0.625000  0.067797  0.041667
1  0.166667  0.416667  0.067797  0.041667
2  0.111111  0.500000  0.050847  0.041667
3  0.083333  0.458333  0.084746  0.041667
4  0.305556  0.791667  0.118644  0.125000

In [23]:
from sklearn.preprocessing  import Binarizer

In [24]:
bb = Binarizer(threshold=5)
bb.fit_transform(df7[['SepalLengthCm']])

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

#converting catagorical variable into  newmaaric

"""
order variable -> order
no order -> neumerical variable
"""

In [25]:
from sklearn.preprocessing  import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['Species'].values)
siz = {'xl':3,"l":2,"m":1}
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1]:
from sklearn.preprocessing  import OneHotEncoder
ohe = OneHotEncoder()
y = ohe.fit_transform(df.iloc[:,4:]).toarray()
pd.get_dummies(y)
y


NameError: name 'df' is not defined

In [ ]:
df.Species.unique()
#26/06/2023
df9 = df.copy(deep = True)
df2.dropna(axis=0,inplace = True)

In [ ]:
mapping = {'Iris-setosa':3,'Iris-versicolor':2, 'Iris-virginica':1}
df9['Species'] = df9['Species'].map(mapping)
df9.head()

In [ ]:
from sklearn.preprocessing  import LabelEncoder
le = LabelEncoder()
df9['Species']  = le.fit_transform(df9[['Species']])
df9


In [ ]:
from sklearn.preprocessing  import OneHotEncoder
ohe = OneHotEncoder()
y = ohe.fit_transform(df9[['Species']]).toarray()
y


In [28]:
pd.get_dummies(df['Species'])

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [ ]:
'''feature selection
SelectKbest 
classicfication problem we use chi2 methord
for regression we use f_regression
'''

In [29]:
from sklearn.feature_selection  import SelectKBest,chi2
# from sklearn.feature_selection  import chi2,f_regression #statical measure chi2 is chai squared

x= df9.iloc[:,0:4]
y= df9['Species']
sk = SelectKBest(chi2,k=2)
sk.fit_transform(x,y)


NameError: name 'df9' is not defined

# feature 

In [36]:
df10 = df.copy(deep = True)
df10.dropna(axis=0,inplace = True)
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x = df10.iloc[:,0:4]
scaled= pca.fit_transform(x)
scaled

array([[-2.75139980e+00,  3.56621639e-01],
       [-2.78600369e+00, -1.40028404e-01],
       [-2.96034481e+00, -1.05605703e-01],
       [-2.81814785e+00, -2.80480066e-01],
       [-2.34426699e+00,  7.75822391e-01],
       [-2.89118787e+00, -4.98047728e-02],
       [-2.96152753e+00, -5.39114435e-01],
       [-2.74392511e+00, -7.76466265e-02],
       [-2.68250852e+00,  5.14185710e-02],
       [-2.85839231e+00, -1.97852375e-01],
       [-3.29832067e+00, -4.69005524e-01],
       [-2.70464116e+00,  1.21553919e+00],
       [-2.44411971e+00,  1.37408253e+00],
       [-2.68648588e+00,  8.48713876e-01],
       [-2.71566403e+00,  3.49281258e-01],
       [-2.26230390e+00,  9.05391562e-01],
       [-2.65333038e+00,  5.50851189e-01],
       [-2.60985424e+00,  4.70246540e-01],
       [-3.28462325e+00,  1.76955629e-01],
       [-2.37204759e+00,  1.33403346e-01],
       [-2.42584435e+00, -3.25004308e-03],
       [-2.57824141e+00, -1.11309794e-01],
       [-2.53773129e+00,  1.67066514e-01],
       [-2.

In [38]:

df_new=pd.DataFrame(scaled)
df_new.head()

0         1
0 -2.751400  0.356622
1 -2.786004 -0.140028
2 -2.960345 -0.105606
3 -2.818148 -0.280480
4 -2.344267  0.775822

In [42]:
from sklearn.preprocessing  import LabelEncoder
le = LabelEncoder()
df_new['Species']=le.fit_transform(df10[['Species']])

/home/rahul/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [44]:
df_new

0         1  Species
0   -2.751400  0.356622        0
1   -2.786004 -0.140028        0
2   -2.960345 -0.105606        0
3   -2.818148 -0.280480        0
4   -2.344267  0.775822        0
..        ...       ...      ...
141  1.875278  0.186313        2
142  1.453316 -0.374859        2
143  1.694765  0.078005        2
144  1.832162  0.117102        2
145  1.317822 -0.280077        2

[146 rows x 3 columns]

# partitioning


In [47]:
x = df_new.iloc[:,0:2]
y = df_new['Species']
from sklearn.model_selection import train_test_split

In [1]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,shuffle=True,random_state=1)#or train_test_split(x,y) , train_test_split(x,y,test_size=0.2) 

NameError: name 'train_test_split' is not defined

In [60]:
xtrain.shape

(116, 2)

In [63]:
ytest.shape

(30,)

In [65]:
xtrain.index


Int64Index([124,  51,  42, 108,  28,  40, 104,  45,  17,  69,
            ...
             25, 134,  71, 129,  79, 133, 137,  72, 140,  37],
           dtype='int64', length=116)

In [67]:
ytest.index

Int64Index([ 98,  66,  53,  75, 121,  74, 119, 128,  44,  58,   5,  16,  90,
             14,  97,  33, 127,  29, 130,  35,  73,  83,  31, 122,  48,  19,
            141, 116,  92,  78],
           dtype='int64')