In [1]:
import numpy as np
a = [x for x in range(0,10)]
np.array(a)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
import pandas as pd
df= pd.read_csv("BMI.csv")

In [7]:
df.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [8]:
df.shape

(500, 4)

In [9]:
df.drop("Gender",inplace=True,axis=1)

In [10]:
df

Height  Weight  Index
0       174      96      4
1       189      87      2
2       185     110      4
3       195     104      3
4       149      61      3
..      ...     ...    ...
495     150     153      5
496     184     121      4
497     141     136      5
498     150      95      5
499     173     131      5

[500 rows x 3 columns]

In [11]:
df[df['Index']==4]

Height  Weight  Index
0       174      96      4
2       185     110      4
9       169     103      4
11      159      80      4
22      169      97      4
..      ...     ...    ...
483     146      85      4
484     188     115      4
485     173     111      4
488     198     136      4
496     184     121      4

[130 rows x 3 columns]